---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  labels:
    app: training-operator
  name: training-operator-metrics-service
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: kubeflow-training-operator
    app.kubernetes.io/name: training-operator
    app.kubernetes.io/part-of: training-operator
status:
  loadBalancer: {}
